# Generated by Django 3.1.3 on 2020-11-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiveFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivepost',
            name='post_body',
            field=models.TextField(default='Body of post here'),
        ),
    ]
