# Generated by Django 3.1.3 on 2020-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiveFeed', '0002_auto_20201115_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivepost',
            name='post_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hivepost',
            name='post_title',
            field=models.CharField(max_length=50),
        ),
    ]
